/*** COPYRIGHT NOTICE AND PUBLIC SOURCE LICENSE ***************************************

	Portions Copyright (c) 1992-2001 Southern Stars Systems.  All Rights Reserved.

	This file contains Original Code and/or Modifications of Original Code as
	defined in and that are subject to the Southern Stars Systems Public Source
	License Version 1.0 (the 'License').  You may not use this file except in
	compliance with the License.  Please obtain a copy of the License at

	http://www.southernstars.com/opensource/

	and read it before using this file.

	The Original Code and all software distributed under the License are distributed
	on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND
	SOUTHERN STARS SYSTEMS HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
	LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
	QUIET ENJOYMENT, OR NON-INFRINGEMENT.  Please see the License for the specific
	language governing rights and limitations under the License.

	CONTRIBUTORS:

	TCD - Tim DeBenedictis (timmyd@southernstars.com)

	MODIFICATION HISTORY:

	1.0.0 - 09 Apr 2001 - TCD - Original Code.

****************************************************************************************/

#include "SkySight.h"

/*** Local function prototypes ***/

static short		TestScreenDepth ( void );
static GWindowPtr	CreateMainWindow ( void );
static void			UpdateCameraExposure ( CameraPtr );

static int			sInitialized = FALSE;
static GPathPtr		sInitialImagePath = NULL;

/***  GMain  ************************************************************/

int GMain ( short event, GWindowPtr window, long param1, long param2 )
{
	int			respond = TRUE;
	CameraPtr	camera;
	
	switch ( event )
	{
		case G_ENTRY_EVENT:

			/*** We need to show the splash screen dialog before creating
			     the main frame window, because the routine which centers
				 the dialog on the screen places the dialog randomly if the
				 dialog's owning window (in this case, the frame window) is
				 hidden.  Of course this problem only affects Windows.  ***/

			if ( TestScreenDepth() == FALSE )
			{
				GExitMainLoop ( 0 );
			}
			else
			{
        		ShowSplashScreen ( G_TICKS_PER_SECOND / 4);

				window = CreateMainWindow();
				if ( window != NULL )
					GMaximizeWindow ( window );

				CreateCameraControlDialog();
            	UpdateMenus();
			}
			
			/*** Supress warning and error messages generated by the TIFF
			     library. ***/
			     
			TIFFSetErrorHandler ( TIFFErrorSupressor );
			TIFFSetWarningHandler ( TIFFErrorSupressor );
			
			sInitialized = TRUE;

			/*** If we got an "open file" event before the program finished
			     initializing, open the file now. ***/
			
			if ( sInitialImagePath != NULL )
			{
				OpenImageFile ( sInitialImagePath );
				GDeletePath ( sInitialImagePath );
			}
			break;

        case G_EXIT_EVENT:
        	DisconnectCamera();
			break;

		case G_MENU_EVENT:
        	DoMenuItem ( param1, param2 );
			break;

		case G_CLOSE_EVENT:
			GDeleteWindow ( window );
			respond = FALSE;
			break;
		
		case G_OPEN_FILE_EVENT:
			
			/*** If we're told to open a file before the program has finished
			     initializing, simply make a copy of the path to the file we're
			     being asked to open; we'll open it after initializing.
			     Otherwise, open the file right now. ***/
			     
			if ( sInitialized == FALSE )
				sInitialImagePath = GCreatePath ( (GPathPtr) param1 );
			else
				OpenImageFile ( (GPathPtr) param1 );
			break;
			
		case G_NULL_EVENT:
			camera = GetActiveCamera();
			if ( camera != NULL )
				UpdateCameraExposure ( camera );
			break;
	}

	return ( respond );
}

/*** UpdateCameraExposure ******************************************************/

void UpdateCameraExposure ( CameraPtr camera )
{
	float	time;
	short	status = GetCameraStatus ( camera, &time, NULL );
	
	/*** If the camera is exposing, update the exposure status
	     displayed in the "Exposure" panel of the "Camera Control"
	     dialog.  If the amount of time elapsed since the start of
	     the exposure exceeds the exposure length, complete the
	     exposure. ***/
	
	if ( status == CAMERA_STATUS_EXPOSING )
	{
        UpdateCameraExposureDialog ( G_TICKS_PER_SECOND / 10 );
        
		if ( time >= GetCameraExposureLength ( camera ) )
		{
			CompleteExposure ( camera );
		}
	}
	
	/*** If the camera is idle, but has another exposure pending,
	     start the exposure. ***/
	     
	if ( status == CAMERA_STATUS_WAITING )
	{
		if ( GetCameraExposure ( camera ) != NULL )
		{
			StartExposure ( camera );
		}
    }
    
    /*** If the camera is exposing or idle, update the camera's
         temperature readout. ***/
         
    if ( status != CAMERA_STATUS_DOWNLOADING )
		UpdateCameraTemperatureDialog ( G_TICKS_PER_SECOND );
}

/*** TestScreenDepth *************************************************************/

short TestScreenDepth ( void )
{
	short	result = TRUE;
	short	depth;
	char	text[256];
	
	depth = GGetScreenDepth();
	if ( depth < 16 )
	{
		sprintf ( text, "SkySight runs best in 16-bit color or higher.  Your monitor is currently displaying %hd-bit color.  Do you want to continue?", depth );
		if ( GDoAlert ( G_INFO_ALERT, G_OK_CANCEL_ALERT, text ) == G_CANCEL_BUTTON )
			result = FALSE;
	}
	
	return ( result );
}

/***  CreateMainWindow  ***********************************************************/

GWindowPtr CreateMainWindow ( void )
{
	char		string[256];
	GWindowPtr	window;
	
    GGetString ( APPLICATION_TITLE_STRING, string );
	window = GCreateFrameWindow ( MAIN_WINDOW, string, -1, -1, -1, -1, FALSE );
	
	/*** Using the native Windows MDI Window Menu functions doesn't seem
         to work, because we are creating MDI windows invisibly.  We'll
         get around this by maintining our own image menu list; see
         BuildImageMenus(). ***/
         
	GSetWindowMenu ( GGetMainMenu ( WINDOW_MENU ) );

	return ( window );
}
